### ISSUE TITLE
Exception The remote certificate is invalid according to the validation procedure

### ISSUE THREAD

**Issue by mzaatar** [fixer-m/snowflake-db-net-client#2]
Hey,
Thanks for providing another library for connecting to Snowflake.

There is an issue with `GetHostName` method in [AuthInfo.cs](https://github.com/fixer-m/snowflake-db-net-client/blob/master/Snowflake.Client/Model/AuthInfo.cs), I failed to use it due to this exception:
Unhandled exception. System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

Do you think we need to change this to be `return $"{Account}.snowflakecomputing.com";` or at least make the `Hostname` parameter that we can set in the ctor same as account and user etc.

**Comment by fixer-m** [comment]
Hi,
Thanks for your bug report!

How your URL looks like when you are logged-in into Snowflake web interface? (You can strip out your account name)

I suppose this issue is related to SSL certificate settings. 
Official client [enforces TLS 1.2](https://github.com/snowflakedb/snowflake-connector-net/blob/1123a710115ad6166d94afd24565b5825b7575eb/Snowflake.Data/Core/HttpUtil.cs#L38) but Snowflake.Client don't - and I think it might be required for some regions.

Can you please prepend your code with these lines (before using Snowflake.Client): 
```csharp
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
ServicePointManager.UseNagleAlgorithm = false;
ServicePointManager.CheckCertificateRevocationList = true;
```
And check if it solves the issue?

**Comment by fixer-m** [comment]
@mzaatar, do you still have this issue?

**Comment by fixer-m** [comment]
@mzaatar, I'm closing this since there is no response for a long time. 
If you still have this issue, you can open new issue. Thanks!
