### ISSUE TITLE
Snowflake old REST API will be switched off by the end of 2021

### ISSUE THREAD

**Issue by vostruk** [fixer-m/snowflake-db-net-client#6]
Snowflake is actively working on changing its current REST API to a new model. Documentation for new API will be available in one month or so and then Snowflake will be closing the old API step by step. 

Due to that some parts of this client would need to be changed soon.

Don't know if you was aware of that or you have a close contact with Snowflake. Just wanted to let you know to be prepared.

**Comment by fixer-m** [comment]
@vostruk, do you have original source of this news? 

I haven't heard anything about it. However, I'm not related anyhow to Snowflake, this might be the actual plan. In this case their **Snowflake.Data** connector and all the other connectors for other platforms will stop work, because they all use current REST API. 

If they are going to update all their connectors, then - of course - I will also be updating **Snowflake.Client** to a new API version. 

> Documentation for new API will be available in one month or so

This would be nice, because their API doesn't have public documentation and right now I have to reverse-engineer it for **Snowflake.Client**. 

Anyway - thanks for this info!

**Comment by VaclavElias** [comment]
> Snowflake is actively working on changing its current REST API to a new model. Documentation for new API will be available in one month or so and then Snowflake will be closing the old API step by step.

@vostruk source?

**Comment by rafael-queiroz-cko** [comment]
> 
> 
> Snowflake is actively working on changing its current REST API to a new model. Documentation for new API will be available in one month or so and then Snowflake will be closing the old API step by step.
> 
> Due to that some parts of this client would need to be changed soon.
> 
> Don't know if you was aware of that or you have a close contact with Snowflake. Just wanted to let you know to be prepared.

sauce?

**Comment by Kingy14** [comment]
> Snowflake is actively working on changing its current REST API to a new model. Documentation for new API will be available in one month or so and then Snowflake will be closing the old API step by step.
> 
> Due to that some parts of this client would need to be changed soon.
> 
> Don't know if you was aware of that or you have a close contact with Snowflake. Just wanted to let you know to be prepared.

Yeah I'm interested in knowing some more if this is the case. Thanks for the info!

**Comment by fvou** [comment]
Since the beginning of the month the new Snowflake REST API is in open preview and it's documentation is publicly available at [Snowlake Docs - Snowflake SQL API](https://docs.snowflake.com/en/developer-guide/sql-api/index.html).
There is however no mention of it replacing the current API, and given the severe limitations it currently has I can't imagine it will.

That said, it might also not be the API @vostruk was talking about, maybe there are more things planned from Snowflake.

**Comment by bculberson** [comment]
This could be closed, the API is definitely not being deprecated anytime soon
